const E=id=>document.getElementById(id),symbols=['🍒','🍋','🍊','🔔','⭐','💎','7️⃣'];
const pay={'🍒':8,'🍋':8,'🍊':10,'🔔':12,'⭐':15,'💎':25,'7️⃣':50};
const LINE_PATTERNS={3:[[1,1,1,1,1]],5:[[1,1,1,1,1],[0,0,0,0,0],[2,2,2,2,2]],7:[[1,1,1,1,1],[0,0,0,0,0],[2,2,2,2,2],[0,1,2,1,0],[2,1,0,1,2]],9:[[1,1,1,1,1],[0,0,0,0,0],[2,2,2,2,2],[0,1,2,1,0],[2,1,0,1,2],[0,0,1,0,0],[2,2,1,2,2],[1,0,0,0,1],[1,2,2,2,1]],15:[[1,1,1,1,1],[0,0,0,0,0],[2,2,2,2,2],[0,1,2,1,0],[2,1,0,1,2],[0,0,1,0,0],[2,2,1,2,2],[1,0,0,0,1],[1,2,2,2,1],[0,1,1,1,0],[2,1,1,1,2],[1,0,1,0,1],[1,2,1,2,1],[0,0,2,0,0],[2,2,0,2,2]]};
let credits=1000,bet=10,lines=5,spinning=false,history=[];const reels=E('reels');
function random(){return symbols[Math.floor(Math.random()*symbols.length)]}
function render(v=Array(5).fill('🍒')){reels.innerHTML=v.map((s,i)=>`<div class="reel" id="reel-${i}"><span class="symbol">${s}</span></div>`).join('')}
function total(){return bet*lines}function update(){E('credits').textContent=credits;E('bet').textContent=bet;E('lines').textContent=lines;E('total').textContent=total()}
function changeBet(d){if(!spinning){bet=Math.max(1,Math.min(100,bet+d));update()}}
function changeLines(d){if(!spinning){const a=[3,5,7,9,15],i=a.indexOf(lines);lines=a[Math.max(0,Math.min(a.length-1,i+(d>0?1:-1)))];update();drawPaylines()}}
E('betDown').onclick=()=>changeBet(-1);E('betUp').onclick=()=>changeBet(1);document.querySelector('[data-line="-1"]').onclick=()=>changeLines(-1);document.querySelector('[data-line="1"]').onclick=()=>changeLines(1);
function drawPaylines(active=[]){document.querySelectorAll('.payline-svg').forEach(x=>x.remove());const slot=document.querySelector('.slot'),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('payline-svg');svg.setAttribute('viewBox','0 0 100 100');svg.setAttribute('preserveAspectRatio','none');LINE_PATTERNS[lines].forEach((p,i)=>{const pts=p.map((r,c)=>`${c*25+12.5},${r*50+25}`).join(' '),el=document.createElementNS('http://www.w3.org/2000/svg','polyline');el.setAttribute('points',pts);el.classList.add('line-path');if(active.includes(i))el.classList.add('active');svg.appendChild(el)});slot.appendChild(svg)}
function evaluate(result){const wins=[];LINE_PATTERNS[lines].forEach((line,index)=>{const vals=line.map((row,col)=>result[col][row]);let count=1;while(count<5&&vals[count]===vals[0])count++;if(count>=3)wins.push({index,symbol:vals[0],count,mult:pay[vals[0]]*(count===4?2:count===5?4:1)})});return wins}
function payout(wins){return wins.reduce((sum,w)=>sum+bet*w.mult,0)}
function addHistory(r,win){history.unshift({r,win});history=history.slice(0,6);const h=E('historyList');if(h)h.innerHTML=history.map(x=>`<span>${x.r.map(col=>col[1]).join(' ')} ${x.win?`<b>+${x.win}</b>`:'—'}</span>`).join('')}
function flash(big=false){const f=E('winFlash');if(!f)return;f.className='win-flash active '+(big?'big':'');setTimeout(()=>f.className='win-flash',900)}
function spin(){const cost=total();if(spinning)return;if(credits<cost){E('message').textContent='Créditos insuficientes';return}spinning=true;credits-=cost;update();E('spin').disabled=true;document.body.classList.add('spinning');drawPaylines();E('message').textContent=`Girando ${lines} líneas...`;const result=Array.from({length:5},()=>[random(),random(),random()]);for(let i=0;i<5;i++){const reel=E(`reel-${i}`),interval=setInterval(()=>reel.querySelector('.symbol').textContent=random(),55);setTimeout(()=>{clearInterval(interval);reel.querySelector('.symbol').textContent=result[i][1];if(i===4)finish(result)},800+i*400)}}
function finish(r){const wins=evaluate(r),win=payout(wins),big=wins.some(w=>w.count>=5||w.mult>=25);spinning=false;E('spin').disabled=false;document.body.classList.remove('spinning');drawPaylines(wins.map(w=>w.index));if(win){credits+=win;E('message').textContent=big?`🔥 ¡JACKPOT! +${win} CRÉDITOS`:`✨ ¡PREMIO! +${win} CRÉDITOS`;flash(big)}else E('message').textContent='Sin premio — ¡sigue girando!';addHistory(r,win);update();setTimeout(()=>drawPaylines(),2200)}
E('spin').onclick=spin;render();update();drawPaylines();
