const E=id=>document.getElementById(id),symbols=['🍒','🍋','🍊','🔔','⭐','💎','7️⃣'];
const pay={'🍒':8,'🍋':8,'🍊':10,'🔔':12,'⭐':15,'💎':25,'7️⃣':50};
const LINE_PATTERNS={1:[[0,0,0]],2:[[0,0,0],[1,1,1]],3:[[0,0,0],[1,1,1],[2,2,2]],5:[[0,0,0],[1,1,1],[2,2,2],[0,1,2],[2,1,0]],7:[[0,0,0],[1,1,1],[2,2,2],[0,1,2],[2,1,0],[0,0,1],[2,2,1]]};
let credits=1000,bet=10,lines=3,spinning=false,history=[];const reels=E('reels');
function random(){return symbols[Math.floor(Math.random()*symbols.length)]}
function render(v=['🍒','🔔','7️⃣']){reels.innerHTML=v.map((s,i)=>`<div class="reel" id="reel-${i}"><span class="symbol">${s}</span></div>`).join('')}
function total(){return bet*lines}function update(){E('credits').textContent=credits;E('bet').textContent=bet;E('lines').textContent=lines;E('total').textContent=total()}
function changeBet(d){if(!spinning){bet=Math.max(1,Math.min(100,bet+d));update()}}
function changeLines(d){if(!spinning){const a=[1,2,3,5,7],i=a.indexOf(lines);lines=a[Math.max(0,Math.min(a.length-1,i+(d>0?1:-1)))];update();drawPaylines()}}
E('betDown').onclick=()=>changeBet(-1);E('betUp').onclick=()=>changeBet(1);document.querySelector('[data-line="-1"]').onclick=()=>changeLines(-1);document.querySelector('[data-line="1"]').onclick=()=>changeLines(1);
function drawPaylines(active=[]){document.querySelectorAll('.payline-svg').forEach(x=>x.remove());const slot=document.querySelector('.slot'),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('payline-svg');svg.setAttribute('viewBox','0 0 100 100');svg.setAttribute('preserveAspectRatio','none');LINE_PATTERNS[lines].forEach((p,i)=>{const pts=p.map((r,c)=>`${c*50+25},${r*50+25}`).join(' '),el=document.createElementNS('http://www.w3.org/2000/svg','polyline');el.setAttribute('points',pts);el.classList.add('line-path');if(active.includes(i))el.classList.add('active');svg.appendChild(el)});slot.appendChild(svg)}
function evaluate(result){const wins=[];LINE_PATTERNS[lines].forEach((line,index)=>{const vals=line.map((row,col)=>result[col]);if(vals[0]===vals[1]&&vals[1]===vals[2])wins.push({index,symbol:vals[0],mult:pay[vals[0]]});else if(vals[0]===vals[1]||vals[1]===vals[2]||vals[0]===vals[2])wins.push({index,symbol:'DOUBLE',mult:2})});return wins}
function payout(wins){return wins.reduce((sum,w)=>sum+bet*w.mult,0)}
function addHistory(r,win){history.unshift({r,win});history=history.slice(0,6);const h=E('historyList');if(h)h.innerHTML=history.map(x=>`<span>${x.r.join(' ')} ${x.win?`<b>+${x.win}</b>`:'—'}</span>`).join('')}
function flash(big=false){const f=E('winFlash');if(!f)return;f.className='win-flash active '+(big?'big':'');setTimeout(()=>f.className='win-flash',800)}
function spin(){const cost=total();if(spinning)return;if(credits<cost){E('message').textContent='Créditos insuficientes';return}spinning=true;credits-=cost;update();E('spin').disabled=true;document.body.classList.add('spinning');drawPaylines();E('message').textContent=`Girando ${lines} líneas...`;const result=[random(),random(),random()];[0,1,2].forEach(i=>{const reel=E(`reel-${i}`),interval=setInterval(()=>reel.querySelector('.symbol').textContent=random(),55);setTimeout(()=>{clearInterval(interval);reel.querySelector('.symbol').textContent=result[i];if(i===2)finish(result)},850+i*450)})}
function finish(r){const wins=evaluate(r),win=payout(wins),triple=wins.some(w=>w.mult>=15);spinning=false;E('spin').disabled=false;document.body.classList.remove('spinning');drawPaylines(wins.map(w=>w.index));if(win){credits+=win;E('message').textContent=triple?`🔥 ¡JACKPOT! +${win} CRÉDITOS`:`✨ ¡PREMIO! +${win} CRÉDITOS`;flash(triple)}else E('message').textContent='Sin premio — ¡sigue girando!';addHistory(r,win);update();setTimeout(()=>drawPaylines(),1800)}
E('spin').onclick=spin;render();update();drawPaylines();
